### ISSUE TITLE
Tracking Issue: V1

### ISSUE THREAD

**Issue by MierenManz** [MierenManz/cards#1]
# Tracking of progress for myself

### HTML/CSS

- [x] Main Menu
- - [x] Write Join button
- - [x] Write Create button
- - [x] Write Name input
- [x] Game
- - [x] Write leave button
- - [x] Write timer till lobby stops
- - [x] Write chat bar
  
### Frontend TS
- [ ] Write DOM Manipulation code
- - [x] Write playername system
- - [x] Write Chat input system
- - [x] Write Error input system
- [x] GameState
- - [x] addCard (only private deck)
- - [x] removeCard (dead cards)
- - [x] modifyCard (only public deck)
- - [x] moveCard (move from private to public deck)
- [x] Write Lobby code
- - [x] Write match creation system
- - [x] Write match join system

- [ ] Write websocket IO system
- - [x] Write output handler for player
- - [ ] Write input handler for player

### UI
- [ ] Write lobby table with player
- [ ] Match board
- - [ ] Write card-deck
- - [ ] Write card-element
- - - [ ] Health
- - - [ ] Name
- - - [ ] Ability
- - - [ ] Image
- - [ ] Write player UI 
- - - [ ] Hand of cards
- - - [ ] Write Mana bar
- - - [ ] Write Health bar
- - - [ ] Write ability button (standard dom)
- - - [ ] Write attack button (standard dom)
- - - [ ] Write draw button (standard dom)
- - [ ] Enemy UI
- - - [ ] Hand of cards (only the back)
- - - [ ] Write Health bar

### Player
- [x] Write onX API
- - [x] onError
- - [x] onOpen
- - [x] onClose
- - [x] onMessage
- [x] Write destructor API `cleanUp`
- [x] Output system `sendEvent` (send event to client)

### Game
- [x] Write stopping functionality
- [x] Write cancelling match functionality
- [x] Write match timeout
- [x] `messageHandler`
- [x] IO System
- - [x] `sendGlobalEvent` System (only players)

### Database
- [ ] Write basic queries for `matches` table (show win loss etc.)

### Closing codes
- [x] OK
- [x] Player left game
- [x] Player left game (error)
- [x] Player won (unused right now)
- [x] Player lost (unused right now)
- [x] Match cancelled
- [x] Match lobby was closed by server (unused right now)

### Game state
- [x] Add card to played deck
- [x] Remove card from played deck
- [x] Modify card from played deck

### Game Logic
- [x] Verify payloads
- [x] Attack card
- [x] Attack opponent
- [x] Draw card
- [x] Lose/Win game
- [x] Use ability

### Replay
- [ ] Save match data
- - [ ] Save replay of events
- - [ ] Save replay of chat (optionally)
- [ ] Replay Format
- [ ] Replay Viewer

### Logger
- [x] Log method
- [x] Debug method
- [x] Info method
- [x] Error method
- [x] Critical Error method
- [x] Auto-create log-files
- [x] Log to file
- [x] Parseable format for debugging later

### Cache
- [x] File cache
- - [x] Regular files
- - [x] SWC transpiling of TS files
- [x] CardCache
- [ ] Jason cache for validation

# Future Ideas (not v1)
- User pages
- Create Account
- Dark mode
- Spectator mode (easily cheatable for now...)
